import Container from '@/components/layout/header/Container'
import './globals.css';
import Header from '@/components/layout/header/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header/>
        {children}
        </Container>
      </body>
      
    </html>
  )
}
