// app/layout.tsx
import Container from '@/components/layout/header/Container'
import './globals.css';
import Header from '@/components/layout/header/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-900 text-white">  {/* Fondo general opcional */}
        <Container>
          <Header />          {/* Navbar */}
          <main className="flex-1">  {/* Opcional: para que ocupe el espacio */}
            {children}        {/* Todas las páginas van aquí */}
          </main>
        </Container>
      </body>
    </html>
  )
}